
export const OUTPATIENT_LIST_REQUEST = "OUTPATIENT_LIST_REQUEST"
export const OUTPATIENT_LIST_SUCCESS = "OUTPATIENT_LIST_SUCCESS"
export const OUTPATIENT_LIST_FAIL = "OUTPATIENT_LIST_FAIL"
export const OUTPATIENT_LIST_RESET = "OUTPATIENT_LIST_RESET"
