export const QY_SYMPTOMS_LIST_REQUEST = 'QY_SYMPTOMS_LIST_REQUEST';
export const QY_SYMPTOMS_LIST_SUCCESS = 'QY_SYMPTOMS_LIST_SUCCESS';
export const QY_SYMPTOMS_LIST_FAIL = 'QY_SYMPTOMS_LIST_FAIL';
export const QY_SYMPTOMS_LIST_RESET = "QY_SYMPTOMS_LIST_RESET"

export const QY_SIGNS_LIST_REQUEST = 'QY_SIGNS_LIST_REQUEST';
export const QY_SIGNS_LIST_SUCCESS = 'QY_SIGNS_LIST_SUCCESS';
export const QY_SIGNS_LIST_FAIL = 'QY_SIGNS_LIST_FAIL';
export const QY_SIGNS_LIST_RESET = "QY_SIGNS_LIST_RESET"

export const QY_HMS_LIST_REQUEST = 'QY_HMS_LIST_REQUEST';
export const QY_HMS_LIST_SUCCESS = 'QY_HMS_LIST_SUCCESS';
export const QY_HMS_LIST_FAIL = 'QY_HMS_LIST_FAIL';
export const QY_HMS_LIST_RESET = "QY_HMS_LIST_RESET"


export const QY_LAB_TEST_LIST_REQUEST = 'QY_LAB_TEST_LIST_REQUEST';
export const QY_LAB_TEST_LIST_SUCCESS = 'QY_LAB_TEST_LIST_SUCCESS';
export const QY_LAB_TEST_LIST_FAIL = 'QY_LAB_TEST_LIST_FAIL';
export const QY_LAB_TEST_LIST_RESET = "QY_LAB_TEST_LIST_RESET"


export const QY_RADIOLOGY_TEST_LIST_REQUEST = 'QY_RADIOLOGY_TEST_LIST_REQUEST';
export const QY_RADIOLOGY_TEST_LIST_SUCCESS = 'QY_RADIOLOGY_TEST_LIST_SUCCESS';
export const QY_RADIOLOGY_TEST_LIST_FAIL = 'QY_RADIOLOGY_TEST_LIST_FAIL';
export const QY_RADIOLOGY_TEST_LIST_RESET = "QY_RADIOLOGY_TEST_LIST_RESET"

export const QY_DIAGNOSIS_LIST_REQUEST = 'QY_DIAGNOSIS_LIST_REQUEST';
export const QY_DIAGNOSIS_LIST_SUCCESS = 'QY_DIAGNOSIS_LIST_SUCCESS';
export const QY_DIAGNOSIS_LIST_FAIL = 'QY_DIAGNOSIS_LIST_FAIL';
export const QY_DIAGNOSIS_LIST_RESET = "QY_DIAGNOSIS_LIST_RESET"