
export const branches = [
  { value: "BRAESIDE", label: "Braeside Branch" },
  { value: "BUSTANI", label: "Bustani Branch" },
  { value: "MUTHITHI", label: "Muthithi Branch" },
  { value: "NYALI", label: "Nyali Branch" },
  { value: "UPPER-HILL", label: "CHG - Upper Hill Medical Center" },
  { value: "WESTLANDS", label: "Westlands Branch" },
];

export const paymentmodeOptions = [
  { value: "1", label: "Corporate" },

  { value: "2", label: "Cash" },
]

export const COUNTRIES_LIST_REQUEST = "COUNTRIES_LIST_REQUEST";
export const COUNTRIES_LIST_SUCCESS = "COUNTRIES_LIST_SUCCESS";
export const COUNTRIES_LIST_FAIL = "COUNTRIES_LIST_FAIL";
export const COUNTRIES_LIST_RESET = "COUNTRIES_LIST_RESET";


export const COUNTIES_LIST_REQUEST = "COUNTIES_LIST_REQUEST";
export const COUNTIES_LIST_SUCCESS = "COUNTIES_LIST_SUCCESS";
export const COUNTIES_LIST_FAIL = "COUNTIES_LIST_FAIL";
export const COUNTIES_LIST_RESET = "COUNTIES_LIST_RESET";


export const SUB_COUNTIES_LIST_SUCCESS = "SUB_COUNTIES_LIST_SUCCESS";
export const SUB_COUNTIES_LIST_REQUEST = "SUB_COUNTIES_LIST_REQUEST";
export const SUB_COUNTIES_LIST_FAIL = "SUB_COUNTIES_LIST_FAIL";
export const SUB_COUNTIES_LIST_RESET = "SUB_COUNTIES_LIST_RESET";


export const CLINICS_LIST_REQUEST = "CLINICS_LIST_REQUEST";
export const CLINICS_LIST_SUCCESS = "CLINICS_LIST_SUCCESS";
export const CLINICS_LIST_FAIL = "CLINICS_LIST_FAIL";
export const CLINICS_LIST_RESET = "CLINICS_LIST_RESET";

export const KINS_LIST_REQUEST = "KINS_LIST_REQUEST";
export const KINS_LIST_SUCCESS = "KINS_LIST_SUCCESS";
export const KINS_LIST_FAIL = "KINS_LIST_FAIL";
export const KINS_LIST_RESET = "KINS_LIST_RESET";


export const INSURANCE_LIST_REQUEST = "INSURANCE_LIST_REQUEST";
export const INSURANCE_LIST_SUCCESS = "INSURANCE_LIST_SUCCESS";
export const INSURANCE_LIST_FAIL = "INSURANCE_LIST_FAIL";
export const INSURANCE_LIST_RESET = "INSURANCE_LIST_RESET";

export const MARKETING_LIST_REQUEST = "MARKETING_LIST_REQUEST";
export const MARKETING_LIST_SUCCESS = "MARKETING_LIST_SUCCESS";
export const MARKETING_LIST_FAIL = "MARKETING_LIST_FAIL";
export const MARKETING_LIST_RESET = "MARKETING_LIST_RESET";

export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL="DOCTOR_LIST_FAIL";
export const DOCTOR_LIST_RESET="DOCTOR_LIST_RESET";

export const EMPLOYEES_LIST_REQUEST = "EMPLOYEES_LIST_REQUEST";
export const EMPLOYEES_LIST_SUCCESS = "EMPLOYEES_LIST_SUCCESS";
export const EMPLYEES_LIST_FAIL="EMPLYEES_LIST_FAIL";
export const EMPLOYEES_LIST_RESET="EMPLOYEES_LIST_RESET";