export const TRIAGE_VISIT_REQUEST = "TRIAGE_VISIT_REQUEST";
export const TRIAGE_VISIT_SUCCESS = "TRIAGE_VISIT_SUCCESS";
export const TRIAGE_VISIT_FAIL = "TRIAGE_VISIT_FAIL";
export const TRIAGE_VISIT_RESET = "TRIAGE_VISIT_RESET";

export const TRIAGE_VISIT_LIST_REQUEST = "TRIAGE_VISIT_LIST_REQUEST";
export const TRIAGE_VISIT_LIST_SUCCESS = "TRIAGE_VISIT_LIST_SUCCESS";
export const TRIAGE_VISIT_LIST_FAIL = "TRIAGE_VISIT_LIST_FAIL";
export const TRIAGE_VISIT_LIST_RESET = "TRIAGE_VISIT_LIST_RESET";