export const REGISTER_VISITOR_REQUEST = "REGISTER_VISITOR_REQUEST";
export const REGISTER_VISITOR_SUCCESS = "REGISTER_VISITOR_SUCCESS";
export const REGISTER_VISITOR_FAIL = "REGISTER_VISITOR_FAIL";
export const REGISTER_VISITOR_RESET = "REGISTER_VISITOR_RESET";

export const ADMIT_VISITOR_REQUEST = "ADMIT_VISITOR_REQUEST";
export const ADMIT_VISITOR_SUCCESS = "ADMIT_VISITOR_SUCCESS";
export const ADMIT_VISITOR_FAIL = "ADMIT_VISITOR_FAIL";
export const ADMIT_VISITOR_RESET = "ADMIT_VISITOR_RESET";

export const VISITORS_LIST_REQUEST = "VISITORS_LIST_REQUEST";
export const VISITORS_LIST_SUCCESS = "VISITORS_LIST_SUCCESS";
export const VISITORS_LIST_FAIL = "VISITORS_LIST_FAIL";
export const VISITORS_LIST_RESET = "VISITORS_LIST_RESET";

export const VISITOR_DETAILS_REQUEST = "VISITOR_DETAILS_REQUEST";
export const VISITOR_DETAILS_SUCCESS = "VISITOR_DETAILS_SUCCESS";
export const VISITOR_DETAILS_FAIL = "VISITOR_DETAILS_FAIL";
export const VISITOR_DETAILS_RESET = "VISITOR_DETAILS_RESET";

export const VISITOR_BY_ID_REQUEST = "VISITOR_BY_ID_REQUEST";
export const VISITOR_BY_ID_SUCCESS = "VISITOR_BY_ID_SUCCESS";
export const VISITOR_BY_ID_FAIL = "VISITOR_BY_ID_FAIL";
export const VISITOR_BY_ID_RESET = "VISITOR_BY_ID_RESET";

export const VISITOR_CLEARANCE_REQUEST="VISITOR_CLEARANCE_REQUEST";
export const VISITOR_CLEARANCE_SUCCESS="VISITOR_CLEARANCE_SUCCESS";
export const VISITOR_CLEARANCE_FAIL="VISITOR_CLEARANCE_FAIL";
export const VISITOR_CLEARANCE_RESET="VISITOR_CLEARANCE_RESET"