import { combineReducers } from "@reduxjs/toolkit";
import { otpVerifyReducer, userLoginReducer, userRegisterReducer,forgotPwdReducer,resetPwdReducer } from "./userReducer";
import { activePatientsReducer, appmntListReducer, convertPatientReducer, patientByNoReducer, patientCreateReducer, patientListReducer, patientTriageVisitCreateReducer, postDoctorTreatmentReducer, postPatientVitalsReducer, postTriageVisitReducer } from "./patientReducer";
import { countiesListReducer, countriesListReducer, subCountiesListReducer, clinicsListReducer, getrelationshipOptionsReducer, getInsuranceReducer, getdoctorListReducer, getemployeesListReducer, getmarketingStrategiesReducer } from "./DropdownReducer";
import { triageWaitingListReducer } from "./TriageReducers";
import { admitVisitorReducer, visitorCreateReducer, visitorListReducer } from "./visitorsReducer";
import { updateTriageListVitalsReducer } from "./triage-reducers/updateTriageListVitalsReducer";

export const rootReducer = combineReducers({
    userLogin:userLoginReducer,
    otpVerify:otpVerifyReducer,
    userRegister:userRegisterReducer,
    forgotPwd:forgotPwdReducer,
    resetPwd:resetPwdReducer,
    createPatient:patientCreateReducer,
    convertPatient:convertPatientReducer,
    countriesList:countriesListReducer,
    countiesList:countiesListReducer,
    subCounties:subCountiesListReducer,
    clinics:clinicsListReducer,
    kinsRelations:getrelationshipOptionsReducer,
    createTriageVisit:patientTriageVisitCreateReducer,
    patientList:patientListReducer,
    activePatients:activePatientsReducer,
    getPatientByNo:patientByNoReducer,
    getInsurance:getInsuranceReducer,
    getDoctorsList:getdoctorListReducer,
    getEmployees:getemployeesListReducer,
    postTriageVisit:postTriageVisitReducer,
    marketingList:getmarketingStrategiesReducer,
   // triageList:triageListReducer,
    postPatientVitals:postPatientVitalsReducer,
    postDoctorTreatment:postDoctorTreatmentReducer,
    // loadUserInfo:loadUserInfo,
    getTriageWaitingList:getTriageWaitingListReducer,
    registerVisitor:visitorCreateReducer,
    visitorsList:visitorListReducer,
    getTriageList:getTriageListReducer,
    triageWaitingList:triageWaitingListReducer,
    registerVisitor:visitorCreateReducer,
    visitorsList:visitorListReducer,
    admitVisitor:admitVisitorReducer,getPatientDetails:getPatientDetailsReducer,
    getTriageListDetails:getTriageListDetailsReducer,
    postTriageListVitals:postTriageListVitalsReducer,
    getVitalsLines:getVitalsLinesReducer,
    postAllergiesMedication:postAllergiesMedicationReducer,
    getAllergiesAndMedications:getAllergiesAndMedicationReducer,
    postInjections:postInjectionsReducer,
    getInjectionNumber:getInjectionNumberReducer,
    getInjections:getInjectionsReducer,
    getStoreRequisitionHeaders:getStoreRequisitionHeadersReducer,
    getItems:getItemsReducer,
    getItemUnits:getItemUnitsOfMeasureReducer,
    postDressings:postDressingsReducer,
    getDressing:getDressingReducer,
    dispatchToDoctor:postDispatchToDoctorReducer,
    checkInPatient:postCheckInPatientReducer,
    appmntList:appmntListReducer,

});